module.exports = [

	// GROUP PROPERTY CONFIG
	// Group Configs set more than one property type and begin with three letters instead of two.
	{matcher:'topL',noParams:true,styles:{'position':'absolute !important','top':'0 !important','left':'0 !important'}},
	{matcher:'topR',noParams:true,styles:{'position':'absolute !important','top':'0 !important','right':'0 !important'}},
	{matcher:'btmL',noParams:true,styles:{'position':'absolute !important','bottom':'0 !important','left':'0 !important'}},
	{matcher:'btmR',noParams:true,styles:{'position':'absolute !important','bottom':'0 !important','right':'0 !important'}},

	// SINGLE PROPERTY CONFIG
	// Single Property Configs set one property type and begin with two letters instead of two.

	// Float
	{matcher:'flL',noParams:true,styles:{'float':'left !important'}},
	{matcher:'flR',noParams:true,styles:{'float':'right !important'}},

	// Width
	{matcher:'wd0',noParams:true,styles:{'width':'0 !important'}},
	{matcher:'wd5p',noParams:true,styles:{'width':'5% !important'}},
	{matcher:'wd10p',noParams:true,styles:{'width':'10% !important'}},
	{matcher:'wd15p',noParams:true,styles:{'width':'15% !important'}},
	{matcher:'wd20p',noParams:true,styles:{'width':'20% !important'}},
	{matcher:'wd25p',noParams:true,styles:{'width':'25% !important'}},
	{matcher:'wd30p',noParams:true,styles:{'width':'30% !important'}},
	{matcher:'wd35p',noParams:true,styles:{'width':'35% !important'}},
	{matcher:'wd40p',noParams:true,styles:{'width':'40% !important'}},
	{matcher:'wd45p',noParams:true,styles:{'width':'45% !important'}},
	{matcher:'wd50p',noParams:true,styles:{'width':'50% !important'}},
	{matcher:'wd55p',noParams:true,styles:{'width':'55% !important'}},
	{matcher:'wd60p',noParams:true,styles:{'width':'60% !important'}},
	{matcher:'wd65p',noParams:true,styles:{'width':'65% !important'}},
	{matcher:'wd70p',noParams:true,styles:{'width':'70% !important'}},
	{matcher:'wd75p',noParams:true,styles:{'width':'75% !important'}},
	{matcher:'wd80p',noParams:true,styles:{'width':'80% !important'}},
	{matcher:'wd85p',noParams:true,styles:{'width':'85% !important'}},
	{matcher:'wd90p',noParams:true,styles:{'width':'90% !important'}},
	{matcher:'wd95p',noParams:true,styles:{'width':'95% !important'}},
	{matcher:'wd100p',noParams:true,styles:{'width':'100% !important'}},

	// Height
	{matcher:'ht0',noParams:true,styles:{'height':'0 !important'}},
	{matcher:'ht1r',noParams:true,styles:{'height':'1rem !important'}},
	{matcher:'ht2r',noParams:true,styles:{'height':'2rem !important'}},
	{matcher:'ht3r',noParams:true,styles:{'height':'3rem !important'}},
	{matcher:'ht4r',noParams:true,styles:{'height':'4rem !important'}},
	{matcher:'ht5r',noParams:true,styles:{'height':'5rem !important'}},
	{matcher:'ht6r',noParams:true,styles:{'height':'6rem !important'}},
	{matcher:'ht7r',noParams:true,styles:{'height':'7rem !important'}},
	{matcher:'ht8r',noParams:true,styles:{'height':'8rem !important'}},
	{matcher:'ht9r',noParams:true,styles:{'height':'9rem !important'}},
	{matcher:'ht10r',noParams:true,styles:{'height':'10rem !important'}},

	// Padding
	{matcher:'pd0',noParams:true,styles:{'padding':'0 !important'}},
	{matcher:'pd0-5r',noParams:true,styles:{'padding':'0.5rem !important'}},
	{matcher:'pd1r',noParams:true,styles:{'padding':'1rem !important'}},
	{matcher:'pd1-5r',noParams:true,styles:{'padding':'1.5rem !important'}},
	{matcher:'pd2r',noParams:true,styles:{'padding':'2rem !important'}},
	{matcher:'pd2-5r',noParams:true,styles:{'padding':'2.5rem !important'}},
	{matcher:'pd3r',noParams:true,styles:{'padding':'3rem !important'}},
	{matcher:'pd3-5r',noParams:true,styles:{'padding':'3.5rem !important'}},
	{matcher:'pd4r',noParams:true,styles:{'padding':'4rem !important'}},
	{matcher:'pd4-5r',noParams:true,styles:{'padding':'4.5rem !important'}},
	{matcher:'pd5r',noParams:true,styles:{'padding':'5rem !important'}},
	{matcher:'pd5-5r',noParams:true,styles:{'padding':'5.5rem !important'}},
	{matcher:'pd6r',noParams:true,styles:{'padding':'6rem !important'}},
	{matcher:'pd6-5r',noParams:true,styles:{'padding':'6.5rem !important'}},
	{matcher:'pd7r',noParams:true,styles:{'padding':'7rem !important'}},
	{matcher:'pd7-5r',noParams:true,styles:{'padding':'7.5rem !important'}},
	{matcher:'pd8r',noParams:true,styles:{'padding':'8rem !important'}},
	{matcher:'pd8-5r',noParams:true,styles:{'padding':'8.5rem !important'}},
	{matcher:'pd9r',noParams:true,styles:{'padding':'9rem !important'}},
	{matcher:'pd9-5r',noParams:true,styles:{'padding':'9.5rem !important'}},
	{matcher:'pd10r',noParams:true,styles:{'padding':'10rem !important'}},
	{matcher:'pd10-5r',noParams:true,styles:{'padding':'10.5rem !important'}},

	{matcher:'pdT0',noParams:true,styles:{'padding-top':'0 !important'}},
	{matcher:'pdT0-5r',noParams:true,styles:{'padding-top':'0.5rem !important'}},
	{matcher:'pdT1r',noParams:true,styles:{'padding-top':'1rem !important'}},
	{matcher:'pdT1-5r',noParams:true,styles:{'padding-top':'1.5rem !important'}},
	{matcher:'pdT2r',noParams:true,styles:{'padding-top':'2rem !important'}},
	{matcher:'pdT2-5r',noParams:true,styles:{'padding-top':'2.5rem !important'}},
	{matcher:'pdT3r',noParams:true,styles:{'padding-top':'3rem !important'}},
	{matcher:'pdT3-5r',noParams:true,styles:{'padding-top':'3.5rem !important'}},
	{matcher:'pdT4r',noParams:true,styles:{'padding-top':'4rem !important'}},
	{matcher:'pdT4-5r',noParams:true,styles:{'padding-top':'4.5rem !important'}},
	{matcher:'pdT5r',noParams:true,styles:{'padding-top':'5rem !important'}},
	{matcher:'pdT5-5r',noParams:true,styles:{'padding-top':'5.5rem !important'}},
	{matcher:'pdT6r',noParams:true,styles:{'padding-top':'6rem !important'}},
	{matcher:'pdT6-5r',noParams:true,styles:{'padding-top':'6.5rem !important'}},
	{matcher:'pdT7r',noParams:true,styles:{'padding-top':'7rem !important'}},
	{matcher:'pdT7-5r',noParams:true,styles:{'padding-top':'7.5rem !important'}},
	{matcher:'pdT8r',noParams:true,styles:{'padding-top':'8rem !important'}},
	{matcher:'pdT8-5r',noParams:true,styles:{'padding-top':'8.5rem !important'}},
	{matcher:'pdT9r',noParams:true,styles:{'padding-top':'9rem !important'}},
	{matcher:'pdT9-5r',noParams:true,styles:{'padding-top':'9.5rem !important'}},
	{matcher:'pdT10r',noParams:true,styles:{'padding-top':'10rem !important'}},
	{matcher:'pdT10-5r',noParams:true,styles:{'padding-top':'10.5rem !important'}},

	{matcher:'pdR0',noParams:true,styles:{'padding-right':'0 !important'}},
	{matcher:'pdR0-5r',noParams:true,styles:{'padding-right':'0.5rem !important'}},
	{matcher:'pdR1r',noParams:true,styles:{'padding-right':'1rem !important'}},
	{matcher:'pdR1-5r',noParams:true,styles:{'padding-right':'1.5rem !important'}},
	{matcher:'pdR2r',noParams:true,styles:{'padding-right':'2rem !important'}},
	{matcher:'pdR2-5r',noParams:true,styles:{'padding-right':'2.5rem !important'}},
	{matcher:'pdR3r',noParams:true,styles:{'padding-right':'3rem !important'}},
	{matcher:'pdR3-5r',noParams:true,styles:{'padding-right':'3.5rem !important'}},
	{matcher:'pdR4r',noParams:true,styles:{'padding-right':'4rem !important'}},
	{matcher:'pdR4-5r',noParams:true,styles:{'padding-right':'4.5rem !important'}},
	{matcher:'pdR5r',noParams:true,styles:{'padding-right':'5rem !important'}},
	{matcher:'pdR5-5r',noParams:true,styles:{'padding-right':'5.5rem !important'}},
	{matcher:'pdR6r',noParams:true,styles:{'padding-right':'6rem !important'}},
	{matcher:'pdR6-5r',noParams:true,styles:{'padding-right':'6.5rem !important'}},
	{matcher:'pdR7r',noParams:true,styles:{'padding-right':'7rem !important'}},
	{matcher:'pdR7-5r',noParams:true,styles:{'padding-right':'7.5rem !important'}},
	{matcher:'pdR8r',noParams:true,styles:{'padding-right':'8rem !important'}},
	{matcher:'pdR8-5r',noParams:true,styles:{'padding-right':'8.5rem !important'}},
	{matcher:'pdR9r',noParams:true,styles:{'padding-right':'9rem !important'}},
	{matcher:'pdR9-5r',noParams:true,styles:{'padding-right':'9.5rem !important'}},
	{matcher:'pdR10r',noParams:true,styles:{'padding-right':'10rem !important'}},
	{matcher:'pdR10-5r',noParams:true,styles:{'padding-right':'10.5rem !important'}},

	{matcher:'pdB0',noParams:true,styles:{'padding-bottom':'0 !important'}},
	{matcher:'pdB0-5r',noParams:true,styles:{'padding-bottom':'0.5rem !important'}},
	{matcher:'pdB1r',noParams:true,styles:{'padding-bottom':'1rem !important'}},
	{matcher:'pdB1-5r',noParams:true,styles:{'padding-bottom':'1.5rem !important'}},
	{matcher:'pdB2r',noParams:true,styles:{'padding-bottom':'2rem !important'}},
	{matcher:'pdB2-5r',noParams:true,styles:{'padding-bottom':'2.5rem !important'}},
	{matcher:'pdB3r',noParams:true,styles:{'padding-bottom':'3rem !important'}},
	{matcher:'pdB3-5r',noParams:true,styles:{'padding-bottom':'3.5rem !important'}},
	{matcher:'pdB4r',noParams:true,styles:{'padding-bottom':'4rem !important'}},
	{matcher:'pdB4-5r',noParams:true,styles:{'padding-bottom':'4.5rem !important'}},
	{matcher:'pdB5r',noParams:true,styles:{'padding-bottom':'5rem !important'}},
	{matcher:'pdB5-5r',noParams:true,styles:{'padding-bottom':'5.5rem !important'}},
	{matcher:'pdB6r',noParams:true,styles:{'padding-bottom':'6rem !important'}},
	{matcher:'pdB6-5r',noParams:true,styles:{'padding-bottom':'6.5rem !important'}},
	{matcher:'pdB7r',noParams:true,styles:{'padding-bottom':'7rem !important'}},
	{matcher:'pdB7-5r',noParams:true,styles:{'padding-bottom':'7.5rem !important'}},
	{matcher:'pdB8r',noParams:true,styles:{'padding-bottom':'8rem !important'}},
	{matcher:'pdB8-5r',noParams:true,styles:{'padding-bottom':'8.5rem !important'}},
	{matcher:'pdB9r',noParams:true,styles:{'padding-bottom':'9rem !important'}},
	{matcher:'pdB9-5r',noParams:true,styles:{'padding-bottom':'9.5rem !important'}},
	{matcher:'pdB10r',noParams:true,styles:{'padding-bottom':'10rem !important'}},
	{matcher:'pdB10-5r',noParams:true,styles:{'padding-bottom':'10.5rem !important'}},

	{matcher:'pdL0',noParams:true,styles:{'padding-left':'0 !important'}},
	{matcher:'pdL0-5r',noParams:true,styles:{'padding-left':'0.5rem !important'}},
	{matcher:'pdL1r',noParams:true,styles:{'padding-left':'1rem !important'}},
	{matcher:'pdL1-5r',noParams:true,styles:{'padding-left':'1.5rem !important'}},
	{matcher:'pdL2r',noParams:true,styles:{'padding-left':'2rem !important'}},
	{matcher:'pdL2-5r',noParams:true,styles:{'padding-left':'2.5rem !important'}},
	{matcher:'pdL3r',noParams:true,styles:{'padding-left':'3rem !important'}},
	{matcher:'pdL3-5r',noParams:true,styles:{'padding-left':'3.5rem !important'}},
	{matcher:'pdL4r',noParams:true,styles:{'padding-left':'4rem !important'}},
	{matcher:'pdL4-5r',noParams:true,styles:{'padding-left':'4.5rem !important'}},
	{matcher:'pdL5r',noParams:true,styles:{'padding-left':'5rem !important'}},
	{matcher:'pdL5-5r',noParams:true,styles:{'padding-left':'5.5rem !important'}},
	{matcher:'pdL6r',noParams:true,styles:{'padding-left':'6rem !important'}},
	{matcher:'pdL6-5r',noParams:true,styles:{'padding-left':'6.5rem !important'}},
	{matcher:'pdL7r',noParams:true,styles:{'padding-left':'7rem !important'}},
	{matcher:'pdL7-5r',noParams:true,styles:{'padding-left':'7.5rem !important'}},
	{matcher:'pdL8r',noParams:true,styles:{'padding-left':'8rem !important'}},
	{matcher:'pdL8-5r',noParams:true,styles:{'padding-left':'8.5rem !important'}},
	{matcher:'pdL9r',noParams:true,styles:{'padding-left':'9rem !important'}},
	{matcher:'pdL9-5r',noParams:true,styles:{'padding-left':'9.5rem !important'}},
	{matcher:'pdL10r',noParams:true,styles:{'padding-left':'10rem !important'}},
	{matcher:'pdL10-5r',noParams:true,styles:{'padding-left':'10.5rem !important'}},

	{matcher:'pdLR0',noParams:true,styles:{'padding-left':'0 !important','padding-right':'0rem !important'}},
	{matcher:'pdLR0-5r',noParams:true,styles:{'padding-left':'0.5rem !important','padding-right':'0.5rem !important'}},
	{matcher:'pdLR1r',noParams:true,styles:{'padding-left':'1rem !important','padding-right':'1rem !important'}},
	{matcher:'pdLR1-5r',noParams:true,styles:{'padding-left':'1.5rem !important','padding-right':'1.5rem !important'}},
	{matcher:'pdLR2r',noParams:true,styles:{'padding-left':'2rem !important','padding-right':'2rem !important'}},
	{matcher:'pdLR2-5r',noParams:true,styles:{'padding-left':'2.5rem !important','padding-right':'2.5rem !important'}},
	{matcher:'pdLR3r',noParams:true,styles:{'padding-left':'3rem !important','padding-right':'3rem !important'}},
	{matcher:'pdLR3-5r',noParams:true,styles:{'padding-left':'3.5rem !important','padding-right':'3.5rem !important'}},
	{matcher:'pdLR4r',noParams:true,styles:{'padding-left':'4rem !important','padding-right':'4rem !important'}},
	{matcher:'pdLR4-5r',noParams:true,styles:{'padding-left':'4.5rem !important','padding-right':'4.5rem !important'}},
	{matcher:'pdLR5r',noParams:true,styles:{'padding-left':'5rem !important','padding-right':'5rem !important'}},
	{matcher:'pdLR5-5r',noParams:true,styles:{'padding-left':'5.5rem !important','padding-right':'5.5rem !important'}},
	{matcher:'pdLR6r',noParams:true,styles:{'padding-left':'6rem !important','padding-right':'6rem !important'}},
	{matcher:'pdLR6-5r',noParams:true,styles:{'padding-left':'6.5rem !important','padding-right':'6.5rem !important'}},
	{matcher:'pdLR7r',noParams:true,styles:{'padding-left':'7rem !important','padding-right':'7rem !important'}},
	{matcher:'pdLR7-5r',noParams:true,styles:{'padding-left':'7.5rem !important','padding-right':'7.5rem !important'}},
	{matcher:'pdLR8r',noParams:true,styles:{'padding-left':'8rem !important','padding-right':'8rem !important'}},
	{matcher:'pdLR8-5r',noParams:true,styles:{'padding-left':'8.5rem !important','padding-right':'8.5rem !important'}},
	{matcher:'pdLR9r',noParams:true,styles:{'padding-left':'9rem !important','padding-right':'9rem !important'}},
	{matcher:'pdLR9-5r',noParams:true,styles:{'padding-left':'9.5rem !important','padding-right':'9.5rem !important'}},
	{matcher:'pdLR10r',noParams:true,styles:{'padding-left':'10rem !important','padding-right':'10rem !important'}},
	{matcher:'pdLR10-5r',noParams:true,styles:{'padding-left':'10.5rem !important','padding-right':'10.5rem !important'}},

	{matcher:'pdTB0',noParams:true,styles:{'padding-top':'0 !important','padding-bottom':'0rem !important'}},
	{matcher:'pdTB0-5r',noParams:true,styles:{'padding-top':'0.5rem !important','padding-bottom':'0.5rem !important'}},
	{matcher:'pdTB1r',noParams:true,styles:{'padding-top':'1rem !important','padding-bottom':'1rem !important'}},
	{matcher:'pdTB1-5r',noParams:true,styles:{'padding-top':'1.5rem !important','padding-bottom':'1.5rem !important'}},
	{matcher:'pdTB2r',noParams:true,styles:{'padding-top':'2rem !important','padding-bottom':'2rem !important'}},
	{matcher:'pdTB2-5r',noParams:true,styles:{'padding-top':'2.5rem !important','padding-bottom':'2.5rem !important'}},
	{matcher:'pdTB3r',noParams:true,styles:{'padding-top':'3rem !important','padding-bottom':'3rem !important'}},
	{matcher:'pdTB3-5r',noParams:true,styles:{'padding-top':'3.5rem !important','padding-bottom':'3.5rem !important'}},
	{matcher:'pdTB4r',noParams:true,styles:{'padding-top':'4rem !important','padding-bottom':'4rem !important'}},
	{matcher:'pdTB4-5r',noParams:true,styles:{'padding-top':'4.5rem !important','padding-bottom':'4.5rem !important'}},
	{matcher:'pdTB5r',noParams:true,styles:{'padding-top':'5rem !important','padding-bottom':'5rem !important'}},
	{matcher:'pdTB5-5r',noParams:true,styles:{'padding-top':'5.5rem !important','padding-bottom':'5.5rem !important'}},
	{matcher:'pdTB6r',noParams:true,styles:{'padding-top':'6rem !important','padding-bottom':'6rem !important'}},
	{matcher:'pdTB6-5r',noParams:true,styles:{'padding-top':'6.5rem !important','padding-bottom':'6.5rem !important'}},
	{matcher:'pdTB7r',noParams:true,styles:{'padding-top':'7rem !important','padding-bottom':'7rem !important'}},
	{matcher:'pdTB7-5r',noParams:true,styles:{'padding-top':'7.5rem !important','padding-bottom':'7.5rem !important'}},
	{matcher:'pdTB8r',noParams:true,styles:{'padding-top':'8rem !important','padding-bottom':'8rem !important'}},
	{matcher:'pdTB8-5r',noParams:true,styles:{'padding-top':'8.5rem !important','padding-bottom':'8.5rem !important'}},
	{matcher:'pdTB9r',noParams:true,styles:{'padding-top':'9rem !important','padding-bottom':'9rem !important'}},
	{matcher:'pdTB9-5r',noParams:true,styles:{'padding-top':'9.5rem !important','padding-bottom':'9.5rem !important'}},
	{matcher:'pdTB10r',noParams:true,styles:{'padding-top':'10rem !important','padding-bottom':'10rem !important'}},

	// Margin
	{matcher:'mg0',noParams:true,styles:{'margin':'0 !important'}},
	{matcher:'mg0-5r',noParams:true,styles:{'margin':'0.5rem !important'}},
	{matcher:'mg1r',noParams:true,styles:{'margin':'1rem !important'}},
	{matcher:'mg1-5r',noParams:true,styles:{'margin':'1.5rem !important'}},
	{matcher:'mg2r',noParams:true,styles:{'margin':'2rem !important'}},
	{matcher:'mg2-5r',noParams:true,styles:{'margin':'2.5rem !important'}},
	{matcher:'mg3r',noParams:true,styles:{'margin':'3rem !important'}},
	{matcher:'mg3-5r',noParams:true,styles:{'margin':'3.5rem !important'}},
	{matcher:'mg4r',noParams:true,styles:{'margin':'4rem !important'}},
	{matcher:'mg4-5r',noParams:true,styles:{'margin':'4.5rem !important'}},
	{matcher:'mg5r',noParams:true,styles:{'margin':'5rem !important'}},
	{matcher:'mg5-5r',noParams:true,styles:{'margin':'5.5rem !important'}},
	{matcher:'mg6r',noParams:true,styles:{'margin':'6rem !important'}},
	{matcher:'mg6-5r',noParams:true,styles:{'margin':'6.5rem !important'}},
	{matcher:'mg7r',noParams:true,styles:{'margin':'7rem !important'}},
	{matcher:'mg7-5r',noParams:true,styles:{'margin':'7.5rem !important'}},
	{matcher:'mg8r',noParams:true,styles:{'margin':'8rem !important'}},
	{matcher:'mg8-5r',noParams:true,styles:{'margin':'8.5rem !important'}},
	{matcher:'mg9r',noParams:true,styles:{'margin':'9rem !important'}},
	{matcher:'mg9-5r',noParams:true,styles:{'margin':'9.5rem !important'}},
	{matcher:'mg10r',noParams:true,styles:{'margin':'10rem !important'}},

	{matcher:'mgT0',noParams:true,styles:{'margin-top':'0 !important'}},
	{matcher:'mgT0-5r',noParams:true,styles:{'margin-top':'0.5rem !important'}},
	{matcher:'mgT1r',noParams:true,styles:{'margin-top':'1rem !important'}},
	{matcher:'mgT1-5r',noParams:true,styles:{'margin-top':'1.5rem !important'}},
	{matcher:'mgT2r',noParams:true,styles:{'margin-top':'2rem !important'}},
	{matcher:'mgT2-5r',noParams:true,styles:{'margin-top':'2.5rem !important'}},
	{matcher:'mgT3r',noParams:true,styles:{'margin-top':'3rem !important'}},
	{matcher:'mgT3-5r',noParams:true,styles:{'margin-top':'3.5rem !important'}},
	{matcher:'mgT4r',noParams:true,styles:{'margin-top':'4rem !important'}},
	{matcher:'mgT4-5r',noParams:true,styles:{'margin-top':'4.5rem !important'}},
	{matcher:'mgT5r',noParams:true,styles:{'margin-top':'5rem !important'}},
	{matcher:'mgT5-5r',noParams:true,styles:{'margin-top':'5.5rem !important'}},
	{matcher:'mgT6r',noParams:true,styles:{'margin-top':'6rem !important'}},
	{matcher:'mgT6-5r',noParams:true,styles:{'margin-top':'6.5rem !important'}},
	{matcher:'mgT7r',noParams:true,styles:{'margin-top':'7rem !important'}},
	{matcher:'mgT7-5r',noParams:true,styles:{'margin-top':'7.5rem !important'}},
	{matcher:'mgT8r',noParams:true,styles:{'margin-top':'8rem !important'}},
	{matcher:'mgT8-5r',noParams:true,styles:{'margin-top':'8.5rem !important'}},
	{matcher:'mgT9r',noParams:true,styles:{'margin-top':'9rem !important'}},
	{matcher:'mgT9-5r',noParams:true,styles:{'margin-top':'9.5rem !important'}},
	{matcher:'mgT10r',noParams:true,styles:{'margin-top':'10rem !important'}},

	{matcher:'mgR0',noParams:true,styles:{'margin-right':'0 !important'}},
	{matcher:'mgR0-5r',noParams:true,styles:{'margin-right':'0.5rem !important'}},
	{matcher:'mgR1r',noParams:true,styles:{'margin-right':'1rem !important'}},
	{matcher:'mgR1-5r',noParams:true,styles:{'margin-right':'1.5rem !important'}},
	{matcher:'mgR2r',noParams:true,styles:{'margin-right':'2rem !important'}},
	{matcher:'mgR2-5r',noParams:true,styles:{'margin-right':'2.5rem !important'}},
	{matcher:'mgR3r',noParams:true,styles:{'margin-right':'3rem !important'}},
	{matcher:'mgR3-5r',noParams:true,styles:{'margin-right':'3.5rem !important'}},
	{matcher:'mgR4r',noParams:true,styles:{'margin-right':'4rem !important'}},
	{matcher:'mgR4-5r',noParams:true,styles:{'margin-right':'4.5rem !important'}},
	{matcher:'mgR5r',noParams:true,styles:{'margin-right':'5rem !important'}},
	{matcher:'mgR5-5r',noParams:true,styles:{'margin-right':'5.5rem !important'}},
	{matcher:'mgR6r',noParams:true,styles:{'margin-right':'6rem !important'}},
	{matcher:'mgR6-5r',noParams:true,styles:{'margin-right':'6.5rem !important'}},
	{matcher:'mgR7r',noParams:true,styles:{'margin-right':'7rem !important'}},
	{matcher:'mgR7-5r',noParams:true,styles:{'margin-right':'7.5rem !important'}},
	{matcher:'mgR8r',noParams:true,styles:{'margin-right':'8rem !important'}},
	{matcher:'mgR8-5r',noParams:true,styles:{'margin-right':'8.5rem !important'}},
	{matcher:'mgR9r',noParams:true,styles:{'margin-right':'9rem !important'}},
	{matcher:'mgR9-5r',noParams:true,styles:{'margin-right':'9.5rem !important'}},
	{matcher:'mgR10r',noParams:true,styles:{'margin-right':'10rem !important'}},

	{matcher:'mgB0',noParams:true,styles:{'margin-bottom':'0 !important'}},
	{matcher:'mgB0-5r',noParams:true,styles:{'margin-bottom':'0.5rem !important'}},
	{matcher:'mgB1r',noParams:true,styles:{'margin-bottom':'1rem !important'}},
	{matcher:'mgB1-5r',noParams:true,styles:{'margin-bottom':'1.5rem !important'}},
	{matcher:'mgB2r',noParams:true,styles:{'margin-bottom':'2rem !important'}},
	{matcher:'mgB2-5r',noParams:true,styles:{'margin-bottom':'2.5rem !important'}},
	{matcher:'mgB3r',noParams:true,styles:{'margin-bottom':'3rem !important'}},
	{matcher:'mgB3-5r',noParams:true,styles:{'margin-bottom':'3.5rem !important'}},
	{matcher:'mgB4r',noParams:true,styles:{'margin-bottom':'4rem !important'}},
	{matcher:'mgB4-5r',noParams:true,styles:{'margin-bottom':'4.5rem !important'}},
	{matcher:'mgB5r',noParams:true,styles:{'margin-bottom':'5rem !important'}},
	{matcher:'mgB5-5r',noParams:true,styles:{'margin-bottom':'5.5rem !important'}},
	{matcher:'mgB6r',noParams:true,styles:{'margin-bottom':'6rem !important'}},
	{matcher:'mgB6-5r',noParams:true,styles:{'margin-bottom':'6.5rem !important'}},
	{matcher:'mgB7r',noParams:true,styles:{'margin-bottom':'7rem !important'}},
	{matcher:'mgB7-5r',noParams:true,styles:{'margin-bottom':'7.5rem !important'}},
	{matcher:'mgB8r',noParams:true,styles:{'margin-bottom':'8rem !important'}},
	{matcher:'mgB8-5r',noParams:true,styles:{'margin-bottom':'8.5rem !important'}},
	{matcher:'mgB9r',noParams:true,styles:{'margin-bottom':'9rem !important'}},
	{matcher:'mgB9-5r',noParams:true,styles:{'margin-bottom':'9.5rem !important'}},
	{matcher:'mgB10r',noParams:true,styles:{'margin-bottom':'10rem !important'}},

	{matcher:'mgL0',noParams:true,styles:{'margin-left':'0 !important'}},
	{matcher:'mgL0-5r',noParams:true,styles:{'margin-left':'0.5rem !important'}},
	{matcher:'mgL1r',noParams:true,styles:{'margin-left':'1rem !important'}},
	{matcher:'mgL1-5r',noParams:true,styles:{'margin-left':'1.5rem !important'}},
	{matcher:'mgL2r',noParams:true,styles:{'margin-left':'2rem !important'}},
	{matcher:'mgL2-5r',noParams:true,styles:{'margin-left':'2.5rem !important'}},
	{matcher:'mgL3r',noParams:true,styles:{'margin-left':'3rem !important'}},
	{matcher:'mgL3-5r',noParams:true,styles:{'margin-left':'3.5rem !important'}},
	{matcher:'mgL4r',noParams:true,styles:{'margin-left':'4rem !important'}},
	{matcher:'mgL4-5r',noParams:true,styles:{'margin-left':'4.5rem !important'}},
	{matcher:'mgL5r',noParams:true,styles:{'margin-left':'5rem !important'}},
	{matcher:'mgL5-5r',noParams:true,styles:{'margin-left':'5.5rem !important'}},
	{matcher:'mgL6r',noParams:true,styles:{'margin-left':'6rem !important'}},
	{matcher:'mgL6-5r',noParams:true,styles:{'margin-left':'6.5rem !important'}},
	{matcher:'mgL7r',noParams:true,styles:{'margin-left':'7rem !important'}},
	{matcher:'mgL7-5r',noParams:true,styles:{'margin-left':'7.5rem !important'}},
	{matcher:'mgL8r',noParams:true,styles:{'margin-left':'8rem !important'}},
	{matcher:'mgL8-5r',noParams:true,styles:{'margin-left':'8.5rem !important'}},
	{matcher:'mgL9r',noParams:true,styles:{'margin-left':'9rem !important'}},
	{matcher:'mgL9-5r',noParams:true,styles:{'margin-left':'9.5rem !important'}},
	{matcher:'mgL10r',noParams:true,styles:{'margin-left':'10rem !important'}},

	{matcher:'mgLR0',noParams:true,styles:{'margin-left':'0 !important','margin-right':'0 !important'}},
	{matcher:'mgLR0-5r',noParams:true,styles:{'margin-left':'0.5rem !important','margin-right':'0.5rem !important'}},
	{matcher:'mgLR1r',noParams:true,styles:{'margin-left':'1rem !important','margin-right':'1rem !important'}},
	{matcher:'mgLR1-5r',noParams:true,styles:{'margin-left':'1.5rem !important','margin-right':'1.5rem !important'}},
	{matcher:'mgLR2r',noParams:true,styles:{'margin-left':'2rem !important','margin-right':'2rem !important'}},
	{matcher:'mgLR2-5r',noParams:true,styles:{'margin-left':'2.5rem !important','margin-right':'2.5rem !important'}},
	{matcher:'mgLR3r',noParams:true,styles:{'margin-left':'3rem !important','margin-right':'3rem !important'}},
	{matcher:'mgLR3-5r',noParams:true,styles:{'margin-left':'3.5rem !important','margin-right':'3.5rem !important'}},
	{matcher:'mgLR4r',noParams:true,styles:{'margin-left':'4rem !important','margin-right':'4rem !important'}},
	{matcher:'mgLR4-5r',noParams:true,styles:{'margin-left':'4.5rem !important','margin-right':'4.5rem !important'}},
	{matcher:'mgLR5r',noParams:true,styles:{'margin-left':'5rem !important','margin-right':'5rem !important'}},
	{matcher:'mgLR5-5r',noParams:true,styles:{'margin-left':'5.5rem !important','margin-right':'5.5rem !important'}},
	{matcher:'mgLR6r',noParams:true,styles:{'margin-left':'6rem !important','margin-right':'6rem !important'}},
	{matcher:'mgLR6-5r',noParams:true,styles:{'margin-left':'6.5rem !important','margin-right':'6.5rem !important'}},
	{matcher:'mgLR7r',noParams:true,styles:{'margin-left':'7rem !important','margin-right':'7rem !important'}},
	{matcher:'mgLR7-5r',noParams:true,styles:{'margin-left':'7.5rem !important','margin-right':'7.5rem !important'}},
	{matcher:'mgLR8r',noParams:true,styles:{'margin-left':'8rem !important','margin-right':'8rem !important'}},
	{matcher:'mgLR8-5r',noParams:true,styles:{'margin-left':'8.5rem !important','margin-right':'8.5rem !important'}},
	{matcher:'mgLR9r',noParams:true,styles:{'margin-left':'9rem !important','margin-right':'9rem !important'}},
	{matcher:'mgLR9-5r',noParams:true,styles:{'margin-left':'9.5rem !important','margin-right':'9.5rem !important'}},
	{matcher:'mgLR10r',noParams:true,styles:{'margin-left':'10rem !important','margin-right':'10rem !important'}},

	{matcher:'mgTB0',noParams:true,styles:{'margin-top':'0 !important','margin-bottom':'0 !important'}},
	{matcher:'mgTB0-5r',noParams:true,styles:{'margin-top':'0.5rem !important','margin-bottom':'0.5rem !important'}},
	{matcher:'mgTB1r',noParams:true,styles:{'margin-top':'1rem !important','margin-bottom':'1rem !important'}},
	{matcher:'mgTB1-5r',noParams:true,styles:{'margin-top':'1.5rem !important','margin-bottom':'1.5rem !important'}},
	{matcher:'mgTB2r',noParams:true,styles:{'margin-top':'2rem !important','margin-bottom':'2rem !important'}},
	{matcher:'mgTB2-5r',noParams:true,styles:{'margin-top':'2.5rem !important','margin-bottom':'2.5rem !important'}},
	{matcher:'mgTB3r',noParams:true,styles:{'margin-top':'3rem !important','margin-bottom':'3rem !important'}},
	{matcher:'mgTB3-5r',noParams:true,styles:{'margin-top':'3.5rem !important','margin-bottom':'3.5rem !important'}},
	{matcher:'mgTB4r',noParams:true,styles:{'margin-top':'4rem !important','margin-bottom':'4rem !important'}},
	{matcher:'mgTB4-5r',noParams:true,styles:{'margin-top':'4.5rem !important','margin-bottom':'4.5rem !important'}},
	{matcher:'mgTB5r',noParams:true,styles:{'margin-top':'5rem !important','margin-bottom':'5rem !important'}},
	{matcher:'mgTB5-5r',noParams:true,styles:{'margin-top':'5.5rem !important','margin-bottom':'5.5rem !important'}},
	{matcher:'mgTB6r',noParams:true,styles:{'margin-top':'6rem !important','margin-bottom':'6rem !important'}},
	{matcher:'mgTB6-5r',noParams:true,styles:{'margin-top':'6.5rem !important','margin-bottom':'6.5rem !important'}},
	{matcher:'mgTB7r',noParams:true,styles:{'margin-top':'7rem !important','margin-bottom':'7rem !important'}},
	{matcher:'mgTB7-5r',noParams:true,styles:{'margin-top':'7.5rem !important','margin-bottom':'7.5rem !important'}},
	{matcher:'mgTB8r',noParams:true,styles:{'margin-top':'8rem !important','margin-bottom':'8rem !important'}},
	{matcher:'mgTB8-5r',noParams:true,styles:{'margin-top':'8.5rem !important','margin-bottom':'8.5rem !important'}},
	{matcher:'mgTB9r',noParams:true,styles:{'margin-top':'9rem !important','margin-bottom':'9rem !important'}},
	{matcher:'mgTB9-5r',noParams:true,styles:{'margin-top':'9.5rem !important','margin-bottom':'9.5rem !important'}},
	{matcher:'mgTB10r',noParams:true,styles:{'margin-top':'10rem !important','margin-bottom':'10rem !important'}}

];